server:
  port: 8081
  servlet:
    context-path: /boot
spring:
  profiles:
    active: dev
  #person:
    ##  lastName: zhangsan
    ##  age: 18
    ##  boss: false
    ##  birth: 2017/12/2
    ##  maps: {k1: v1, k2: 12}
    ##  lists:
    ##    - lisi
    ##    - zhaoliu
    ##  dog:
  ##    name: 小狗
  ##    age: 2